# -*- coding: utf-8 -*-
"""Données de prononciation pour les cours d'anglais et de français"""

PRONUNCIATION_DATA = {
    "en": {
        "Class 00": {
            "title": "/h/ aspiré",
            "tip": "Le 'h' en anglais SE PRONONCE (contrairement au français).",
            "words": ["house", "hat", "happy", "hello", "have", "help"],
            "phrases": ["Hello, how are you?", "I have a happy house."],
        },
        "Class 01": {
            "title": "/ɪ/ vs /iː/",
            "tip": "Voyelle courte /ɪ/ (ship) vs voyelle longue /iː/ (sheep).",
            "words": ["ship - sheep", "sit - seat", "fit - feet",
                       "live - leave", "it - eat", "bit - beat"],
            "phrases": ["I live on a ship.", "I leave the sheep.",
                         "Sit on the seat."],
        },
        "Class 02": {
            "title": "-ed pronunciation",
            "tip": "/t/, /d/, /ɪd/ — trois façons de prononcer -ed.",
            "words": ["watched", "worked", "stopped",
                       "played", "listened", "cleaned",
                       "wanted", "visited", "needed"],
            "phrases": ["I watched a movie yesterday.",
                         "She played soccer last weekend."],
        },
        "Class 03": {
            "title": "/æ/ vs /e/",
            "tip": "Voyelles courtes /æ/ (cat) et /e/ (bed).",
            "words": ["cat - ket", "bad - bed", "man - men",
                       "had - head", "sad - said", "bat - bet"],
            "phrases": ["The cat sat on the bed.", "The man said hello."],
        },
        "Class 04": {
            "title": "Gonna reduction",
            "tip": "'Going to' devient 'gonna' à l'oral.",
            "words": ["gonna", "wanna", "gotta", "hafta"],
            "phrases": ["I'm gonna study tonight.",
                         "She's gonna work tomorrow."],
        },
        "Class 05": {
            "title": "/ʃ/ vs /tʃ/",
            "tip": "'sh' (shoe) vs 'ch' (chew).",
            "words": ["shoe - chew", "ship - chip", "shop - chop",
                       "wash - watch", "sheep - cheap"],
            "phrases": ["I need a new shoe.", "I want to chew this."],
        },
        "Class 06": {
            "title": "/v/ vs /b/",
            "tip": "/v/ = lèvre-dents, /b/ = deux lèvres.",
            "words": ["vote - boat", "very - berry", "vest - best",
                       "van - ban", "vet - bet"],
            "phrases": ["I vote for the boat.", "Very good, berry nice."],
        },
        "Class 07": {
            "title": "/h/ review",
            "tip": "Révision du /h/ aspiré.",
            "words": ["have", "here", "how", "home", "high school"],
            "phrases": ["How are you?", "I have a home here."],
        },
        "Class 08": {
            "title": "/ŋ/ final",
            "tip": "Son nasal /ŋ/ à la fin des mots.",
            "words": ["sing", "thing", "ring", "king", "long"],
            "phrases": ["I love to sing.", "What a beautiful thing!"],
        },
        "Class 09": {
            "title": "/ɜːr/",
            "tip": "Voyelle longue /ɜːr/ avec un r final.",
            "words": ["bird", "word", "work", "learn", "turn", "girl"],
            "phrases": ["The bird is at work.", "I want to learn more."],
        },
        "Class 10": {
            "title": "/oʊ/ vs /ɔː/",
            "tip": "Diphtongue /oʊ/ (coat) vs voyelle longue /ɔː/ (caught).",
            "words": ["coat - caught", "boat - bought", "note - naught",
                       "so - saw", "low - law"],
            "phrases": ["I bought a coat.", "So, what did you see?"],
        },
        "Class 11": {
            "title": "used to = /ˈjuːstə/",
            "tip": "Le 'd' de 'used to' est silencieux.",
            "words": ["used to", "usta"],
            "phrases": ["I used to play piano.", "She used to live here."],
        },
        "Class 12": {
            "title": "/aɪ/ vs /eɪ/",
            "tip": "Diphtongues /aɪ/ (my) et /eɪ/ (may).",
            "words": ["my - may", "buy - bay", "lie - lay",
                       "pie - pay", "die - day", "high - hey"],
            "phrases": ["I may buy it.", "Hey, that's my pie!"],
        },
        "Class 13": {
            "title": "/aʊ/ vs /oʊ/",
            "tip": "Diphtongues /aʊ/ (now) et /oʊ/ (no).",
            "words": ["now - no", "how - hoe", "cow - coat",
                       "out - oat", "house - hose"],
            "phrases": ["How are you now?", "No, not right now."],
        },
        "Class 14": {
            "title": "Word stress",
            "tip": "L'accent tonique change le sens du mot.",
            "words": ["PREsent / preSENT", "REcord / reCORD",
                       "OBject / obJECT", "PROgress / proGRESS"],
            "phrases": ["I want to present a present.",
                         "Can you record the record?"],
        },
        "Class 15": {
            "title": "Intonation",
            "tip": "Statements = voix descendante. Questions = voix montante.",
            "words": ["I live in Mexico. (fall)",
                       "Do you live in Mexico? (rise)",
                       "Where do you live? (fall)"],
            "phrases": ["I live in Mexico.", "Do you live in Mexico?"],
        },
        "Class 16": {
            "title": "Rhythm",
            "tip": "L'accent tonique des mots.",
            "words": ["baNAna", "comPUter", "YESterday", "toMOrrow"],
            "phrases": ["I need a new computer.",
                         "See you tomorrow!"],
        },
        "Class 17": {
            "title": "Connected speech",
            "tip": "Comment les mots se connectent à l'oral.",
            "words": ["Whaddaya want?", "I'm gonna", "Lemme", "Gimme"],
            "phrases": ["What do you want to do?", "Let me help you."],
        },
        "Class 18": {
            "title": "Reductions",
            "tip": "Formes courtes à l'oral.",
            "words": ["gonna", "wanna", "gotta", "hafta", "'cause"],
            "phrases": ["I'm gonna go.", "I wanna eat.",
                         "I gotta study.", "I hafta work."],
        },
    },
    "fr": {
        "L01": {
            "title": "Voyelles A, E, I, O, U",
            "tip": "Les voyelles françaises sont plus pures qu'en espagnol.",
            "words": ["a", "e", "i", "o", "u", "bonjour", "merci"],
            "phrases": ["Bonjour, je m'appelle Ingrid.", "Merci beaucoup."],
        },
        "L02": {
            "title": "Voyelles nasales on / an / in",
            "tip": "Sons nasaux qui n'existent pas en espagnol.",
            "words": ["bonjour", "français", "mexicain", "dans", "vin"],
            "phrases": ["Je suis mexicaine.", "Il est français."],
        },
        "L03": {
            "title": "Le 'r' français",
            "tip": "Le 'r' est guttural, pas roulé.",
            "words": ["frère", "sœur", "parents", "avoir", "âge", "Paris"],
            "phrases": ["J'ai un frère et une sœur.", "J'ai 15 ans."],
        },
        "L04": {
            "title": "/y/ vs /u/",
            "tip": "Le 'u' français est unique.",
            "words": ["tu - tout", "su - sous", "rue - roue",
                       "une - oune"],
            "phrases": ["Tu veux tout ?", "La rue est longue."],
        },
        "L05": {
            "title": "-er final = /e/",
            "tip": "Les verbes en -er se terminent par /e/.",
            "words": ["parler", "manger", "écouter", "regarder", "aimer"],
            "phrases": ["Je parle français.", "J'aime écouter de la musique."],
        },
        "L06": {
            "title": "Nombres et liaisons",
            "tip": "Les nombres et les liaisons obligatoires.",
            "words": ["un", "deux", "trois", "quatre", "cinq",
                       "deux heures", "trois amis"],
            "phrases": ["Il est deux heures.", "J'ai trois amis."],
        },
        "L07": {
            "title": "Le 'oi' = /wa/",
            "tip": "Le 'oi' se prononce toujours /wa/.",
            "words": ["toi", "moi", "bois", "voiture", "voir", "boire"],
            "phrases": ["Moi, je vais à la voiture.", "Tu bois quoi ?"],
        },
        "L08": {
            "title": "Mon / ma / mes",
            "tip": "Différence entre les possessifs.",
            "words": ["mon père", "ma mère", "mes amis",
                       "ce livre", "cette table"],
            "phrases": ["Mon père est médecin.", "Mes amis sont ici."],
        },
        "L09": {
            "title": "Ne → n' devant voyelle",
            "tip": "Le 'ne' devient 'n'' devant une voyelle.",
            "words": ["je n'aime", "je n'ai", "je n'habite", "je n'oublie"],
            "phrases": ["Je n'aime pas le café.", "Je n'habite pas ici."],
        },
        "L10": {
            "title": "Intonation des questions",
            "tip": "La voix monte à la fin.",
            "words": ["Tu parles ?", "Est-ce que...?", "Où ?", "Comment ?"],
            "phrases": ["Est-ce que tu parles français ?",
                         "Comment tu t'appelles ?"],
        },
        "L11": {
            "title": "Pronoms lui / leur",
            "tip": "/lɥi/ et /lœʁ/.",
            "words": ["lui", "leur", "le", "la", "les"],
            "phrases": ["Je lui parle.", "Je leur écris."],
        },
        "L12": {
            "title": "plus = /ply/ ou /plys/",
            "tip": "Selon le contexte.",
            "words": ["plus grand", "plus intéressant", "le plus"],
            "phrases": ["Il est plus grand que moi.", "C'est le plus beau."],
        },
        "L13": {
            "title": "Participe passé",
            "tip": "Le -e final ne se prononce pas.",
            "words": ["mangé", "parlé", "fini", "vu", "fait", "pris"],
            "phrases": ["J'ai mangé une pizza.", "J'ai vu un film."],
        },
        "L14": {
            "title": "Accord au passé",
            "tip": "L'accord s'entend à l'écrit, pas à l'oral.",
            "words": ["allé", "allée", "venu", "venue", "parti", "partie"],
            "phrases": ["Je suis allé au cinéma.", "Elle est venue hier."],
        },
        "L15": {
            "title": "-ais / -ait = /ɛ/",
            "tip": "Toutes les terminaisons de l'imparfait sonnent pareil.",
            "words": ["j'étais", "j'avais", "j'habitais", "je jouais"],
            "phrases": ["Quand j'étais jeune, j'habitais à Paris."],
        },
        "L16": {
            "title": "Futur simple -ai = /e/",
            "tip": "Attention à ne pas confondre avec le conditionnel.",
            "words": ["mangerai", "partirai", "travaillerai"],
            "phrases": ["Je mangerai à midi.", "Je partirai demain."],
        },
        "L17": {
            "title": "Je voudrais",
            "tip": "/vu.dʁɛ/ — conditionnel de politesse.",
            "words": ["je voudrais", "j'aimerais", "pourriez-vous"],
            "phrases": ["Je voudrais un café, s'il vous plaît."],
        },
        "L18": {
            "title": "qui / que",
            "tip": "Différence sonore claire.",
            "words": ["qui", "que", "où", "dont"],
            "phrases": ["Le livre que je lis.", "La ville où j'habite."],
        },
        "L19": {
            "title": "Révision générale",
            "tip": "Récapitulatif de tous les sons.",
            "words": ["bonjour", "merci", "au revoir", "s'il vous plaît"],
            "phrases": ["Bonjour ! Merci beaucoup. Au revoir !"],
        },
    }
}
