# -*- coding: utf-8 -*-
"""Base de donnees des chansons pour les cours anglais et francais"""

SONGS = {
    "en": {
        "Class 00": {"title": "Hello", "artist": "Adele", "yt": "YQHsXMglC9A", "level": "A1",
            "vocab": ["hello", "meet", "years"],
            "fill": [{"line": "Hello, it's ___", "ans": "me"}, {"line": "I was wondering if after all these ___", "ans": "years"}],
            "quiz": [{"q": "What does she say first?", "a": "Hello, it's me"}, {"q": "How long has it been?", "a": "Many years"}]},
        "Class 01": {"title": "Wake Me Up", "artist": "Avicii", "yt": "IcrbM1l_BoI", "level": "A1",
            "vocab": ["wake up", "morning", "find"],
            "fill": [{"line": "Wake me up when it's all ___", "ans": "over"}, {"line": "Feeling my way through the ___", "ans": "darkness"}],
            "quiz": [{"q": "When should they wake the singer?", "a": "When it's all over"}, {"q": "How does the singer feel?", "a": "Lost in the darkness"}]},
        "Class 02": {"title": "Yesterday", "artist": "The Beatles", "yt": "NrgmdOz227I", "level": "A2",
            "vocab": ["yesterday", "believe", "troubles"],
            "fill": [{"line": "Yesterday, all my ___ seemed so far away", "ans": "troubles"}, {"line": "Oh, I believe in ___", "ans": "yesterday"}],
            "quiz": [{"q": "What does the singer believe in?", "a": "Yesterday"}, {"q": "Where did the troubles seem to be?", "a": "Far away"}]},
        "Class 03": {"title": "Candle in the Wind", "artist": "Elton John", "yt": "3JY2Aq1X0es", "level": "A2",
            "vocab": ["candle", "wind", "remember"],
            "fill": [{"line": "Goodbye, Norma Jean, though I never knew you at ___", "ans": "all"}, {"line": "And it seems to me you lived your life like a ___ in the wind", "ans": "candle"}],
            "quiz": [{"q": "What did the person live like?", "a": "A candle in the wind"}, {"q": "Who is the song about?", "a": "Norma Jean (Marilyn Monroe)"}]},
        "Class 04": {"title": "We Are the Champions", "artist": "Queen", "yt": "04854XqcfCY", "level": "A2",
            "vocab": ["champion", "fight", "time"],
            "fill": [{"line": "We are the ___", "ans": "champions"}, {"line": "And we'll keep on fighting till the ___", "ans": "end"}],
            "quiz": [{"q": "What are they?", "a": "The champions"}, {"q": "Until when will they fight?", "a": "Till the end"}]},
        "Class 05": {"title": "Friday I'm in Love", "artist": "The Cure", "yt": "mGgobC82z1k", "level": "A2",
            "vocab": ["Friday", "Monday", "love"],
            "fill": [{"line": "I don't care if Monday's ___", "ans": "blue"}, {"line": "Friday I'm in ___", "ans": "love"}],
            "quiz": [{"q": "What day is the singer in love?", "a": "Friday"}, {"q": "What color is Monday?", "a": "Blue"}]},
        "Class 06": {"title": "I Still Haven't Found What I'm Looking For", "artist": "U2", "yt": "e3-5YC_oHqk", "level": "B1",
            "vocab": ["found", "looking for", "running"],
            "fill": [{"line": "I have climbed the highest ___", "ans": "mountains"}, {"line": "But I still haven't ___ what I'm looking for", "ans": "found"}],
            "quiz": [{"q": "Has the singer found what he's looking for?", "a": "No, still haven't"}, {"q": "What did he climb?", "a": "The highest mountains"}]},
        "Class 07": {"title": "Have You Ever Seen the Rain", "artist": "Creedence", "yt": "Gu2pVPWGYMQ", "level": "B1",
            "vocab": ["ever", "rain", "sunny"],
            "fill": [{"line": "Have you ever seen the ___?", "ans": "rain"}, {"line": "Coming down on a ___ day", "ans": "sunny"}],
            "quiz": [{"q": "What does the singer ask?", "a": "Have you ever seen the rain?"}, {"q": "When does the rain come?", "a": "On a sunny day"}]},
        "Class 08": {"title": "I've Been Waiting", "artist": "Sixpence None the Richer", "yt": "WugbTU3Z2rA", "level": "B1",
            "vocab": ["waiting", "long time", "wondering"],
            "fill": [{"line": "I've been ___ for a girl like you", "ans": "waiting"}, {"line": "To come into my ___", "ans": "life"}],
            "quiz": [{"q": "Who has the singer been waiting for?", "a": "A girl like you"}, {"q": "Where should she come?", "a": "Into his life"}]},
        "Class 09": {"title": "When You Were Young", "artist": "The Killers", "yt": "ff0oWESdmH0", "level": "B1",
            "vocab": ["young", "waiting", "heart"],
            "fill": [{"line": "When you were ___", "ans": "young"}, {"line": "He doesn't look a thing like ___", "ans": "Jesus"}],
            "quiz": [{"q": "When does the singer talk about?", "a": "When you were young"}, {"q": "What is the person waiting for?", "a": "Something"}]},
        "Class 10": {"title": "The Night They Drove Old Dixie Down", "artist": "The Band", "yt": "Y8LHnFsaKUI", "level": "B1",
            "vocab": ["night", "drove", "down"],
            "fill": [{"line": "The ___ they drove old Dixie down", "ans": "night"}, {"line": "And all the bells were ___", "ans": "ringing"}],
            "quiz": [{"q": "What happened that night?", "a": "They drove old Dixie down"}, {"q": "What did the bells do?", "a": "Ringing"}]},
        "Class 11": {"title": "Used to Love Her", "artist": "Guns N' Roses", "yt": "KvHKkYlUvSk", "level": "B1",
            "vocab": ["used to", "love", "had to"],
            "fill": [{"line": "I used to ___ her", "ans": "love"}, {"line": "But I had to ___ her", "ans": "kill"}],
            "quiz": [{"q": "What did the singer use to do?", "a": "Love her"}, {"q": "What did he have to do?", "a": "Kill her (metaphor)"}]},
        "Class 12": {"title": "The Climb", "artist": "Miley Cyrus", "yt": "ngzC_8zqY_8", "level": "B1",
            "vocab": ["climb", "always", "gonna"],
            "fill": [{"line": "There's always gonna be another ___", "ans": "mountain"}, {"line": "I'm always gonna wanna make it ___", "ans": "move"}],
            "quiz": [{"q": "What will always be there?", "a": "Another mountain"}, {"q": "What will she do?", "a": "Make it move"}]},
        "Class 13": {"title": "If I Were a Boy", "artist": "Beyonce", "yt": "AWpsOqh8q0M", "level": "B2",
            "vocab": ["if I were", "boy", "roll out of bed"],
            "fill": [{"line": "If I were a ___", "ans": "boy"}, {"line": "I think I could understand", "ans": "how"}],
            "quiz": [{"q": "What does the singer say?", "a": "If I were a boy"}, {"q": "What would she do?", "a": "Understand how it feels"}]},
        "Class 14": {"title": "The House That Built Me", "artist": "Miranda Lambert", "yt": "DQYNM6SjD_o", "level": "B2",
            "vocab": ["built", "house", "know"],
            "fill": [{"line": "I thought if I could touch this ___", "ans": "place"}, {"line": "The house that ___ me", "ans": "built"}],
            "quiz": [{"q": "What does she want to touch?", "a": "This place"}, {"q": "What is the house?", "a": "The house that built her"}]},
        "Class 15": {"title": "Somebody Told Me", "artist": "The Killers", "yt": "Y5fBdpreJiU", "level": "B2",
            "vocab": ["told me", "somebody", "boyfriend"],
            "fill": [{"line": "Somebody told me", "ans": "that"}, {"line": "You had a boyfriend", "ans": "that"}],
            "quiz": [{"q": "What did somebody tell?", "a": "You had a boyfriend"}, {"q": "What does the singer ask?", "a": "Are we human or dancer?"}]},
        "Class 16": {"title": "The Man Who Can't Be Moved", "artist": "The Script", "yt": "tZOOZ9nGcpY", "level": "B2",
            "vocab": ["man who", "can't", "moved"],
            "fill": [{"line": "I'm the man who can't be ___", "ans": "moved"}, {"line": "Going back to the corner where I first saw ___", "ans": "you"}],
            "quiz": [{"q": "Who is the singer?", "a": "The man who can't be moved"}, {"q": "Where is he going?", "a": "To the corner"}]},
        "Class 17": {"title": "Shape of You", "artist": "Ed Sheeran", "yt": "JGwWNGJdvx8", "level": "B2",
            "vocab": ["shape", "love", "fall"],
            "fill": [{"line": "I'm in love with the ___ of you", "ans": "shape"}, {"line": "We push and pull like a magnet ___", "ans": "do"}],
            "quiz": [{"q": "What is he in love with?", "a": "The shape of you"}, {"q": "How do they push and pull?", "a": "Like a magnet"}]},
        "Class 18": {"title": "By the Time I Get to Phoenix", "artist": "Glen Campbell", "yt": "hk41-h9sXPU", "level": "B2",
            "vocab": ["by the time", "get to", "rise"],
            "fill": [{"line": "By the time I get to ___", "ans": "Phoenix"}, {"line": "She'll be ___", "ans": "rising"}],
            "quiz": [{"q": "Where is he going?", "a": "Phoenix"}, {"q": "What will she be doing?", "a": "Rising"}]}
    },
    "fr": {
        "L01": {"title": "Derniere Danse", "artist": "Indila", "yt": "K5KAc5CoCuk", "level": "A1",
            "vocab": ["derniere", "danse", "souffrir"],
            "fill": [{"line": "Oh ma douce ___", "ans": "souffrance"}, {"line": "Emporte-moi, emporte-___", "ans": "moi"}],
            "quiz": [{"q": "Qui chante cette chanson?", "a": "Indila"}, {"q": "De quoi parle la chanson?", "a": "De souffrance et de danse"}]},
        "L02": {"title": "Je Suis Chez Moi", "artist": "Black M", "yt": "wSP8ZZsFvIo", "level": "A1",
            "vocab": ["je suis", "chez moi", "rester"],
            "fill": [{"line": "Je suis chez ___", "ans": "moi"}, {"line": "Je reste chez ___", "ans": "moi"}],
            "quiz": [{"q": "Ou est le chanteur?", "a": "Chez lui"}, {"q": "Que fait-il?", "a": "Il reste chez lui"}]},
        "L03": {"title": "J'ai Demande a la Lune", "artist": "Indochine", "yt": "8hZ4DBSjkz0", "level": "A1",
            "vocab": ["j'ai", "demande", "lune"],
            "fill": [{"line": "J'ai demande a la ___", "ans": "lune"}, {"line": "De me donner une ___", "ans": "chance"}],
            "quiz": [{"q": "A qui parle le chanteur?", "a": "A la lune"}, {"q": "Que demande-t-il?", "a": "Une chance"}]},
        "L04": {"title": "Les Champs-Elysees", "artist": "Joe Dassin", "yt": "pPu7WNt5bNo", "level": "A1",
            "vocab": ["les", "champs", "coeur"],
            "fill": [{"line": "Aux Champs-Elysees", "ans": "aux"}, {"line": "Au soleil, sous la pluie", "ans": "pluie"}],
            "quiz": [{"q": "Ou se passe la chanson?", "a": "Aux Champs-Elysees"}, {"q": "A quel moment?", "a": "Au soleil et sous la pluie"}]},
        "L05": {"title": "Je Veux", "artist": "Zaz", "yt": "1LLaNJRX5nw", "level": "A1",
            "vocab": ["je veux", "aimer", "vivre"],
            "fill": [{"line": "Je veux d'l'amour, d'la joie, de la bonne ___", "ans": "humeur"}, {"line": "Ce n'est pas votre ___ qui fera mon bonheur", "ans": "argent"}],
            "quiz": [{"q": "Que veut Zaz?", "a": "Amour, joie, bonne humeur"}, {"q": "Qu'est-ce qui ne fait pas son bonheur?", "a": "L'argent"}]},
        "L06": {"title": "Quelle Heure Est-Il", "artist": "Traditionnel", "yt": "E2gV7mDeKvE", "level": "A1",
            "vocab": ["quelle heure", "temps", "maintenant"],
            "fill": [{"line": "Quelle heure est-___?", "ans": "il"}, {"line": "Il est ___ heures", "ans": "sept"}],
            "quiz": [{"q": "Quelle est la question?", "a": "Quelle heure est-il?"}, {"q": "Quelle heure est-il?", "a": "Sept heures"}]},
        "L07": {"title": "Formidable", "artist": "Stromae", "yt": "S_xH7mSJn8s", "level": "A1",
            "vocab": ["formidable", "amour", "soir"],
            "fill": [{"line": "Formidable, formidable", "ans": "formidable"}, {"line": "Tu etais formidable", "ans": "formidable"}],
            "quiz": [{"q": "Quel est le mot repete?", "a": "Formidable"}, {"q": "Qui chante?", "a": "Stromae"}]},
        "L08": {"title": "Ma Philosophie", "artist": "Amel Bent", "yt": "sN9P1dMNg-k", "level": "A1+",
            "vocab": ["ma", "philosophie", "mon"],
            "fill": [{"line": "C'est ma ___", "ans": "philosophie"}, {"line": "Mon ___ de vivre", "ans": "art"}],
            "quiz": [{"q": "A qui appartient la philosophie?", "a": "A elle (ma)"}, {"q": "Que dit-elle?", "a": "C'est sa philosophie"}]},
        "L09": {"title": "Ne Me Quitte Pas", "artist": "Jacques Brel", "yt": "z4gxvQpYqXI", "level": "A1+",
            "vocab": ["ne me quitte pas", "oublier", "attendre"],
            "fill": [{"line": "Ne me quitte ___", "ans": "pas"}, {"line": "Il faut ___", "ans": "oublier"}],
            "quiz": [{"q": "Que demande Brel?", "a": "Ne me quitte pas"}, {"q": "Que faut-il faire?", "a": "Oublier"}]},
        "L10": {"title": "Papaoutai", "artist": "Stromae", "yt": "am6wE1Gq3rI", "level": "A1+",
            "vocab": ["papa", "ou es-tu", "comprendre"],
            "fill": [{"line": "Papa, ou es-___?", "ans": "tu"}, {"line": "Dis-moi ___", "ans": "pourquoi"}],
            "quiz": [{"q": "A qui parle-t-il?", "a": "A son papa"}, {"q": "Quelle est la question?", "a": "Ou es-tu papa?"}]},
        "L11": {"title": "La Vie en Rose", "artist": "Edith Piaf", "yt": "kFzViYkZ8iE", "level": "A1+",
            "vocab": ["la vie", "rose", "yeux"],
            "fill": [{"line": "La vie en ___", "ans": "rose"}, {"line": "Quand il me prend dans ses ___", "ans": "bras"}],
            "quiz": [{"q": "Quelle est la couleur de la vie?", "a": "Rose"}, {"q": "Que fait-il avec ses bras?", "a": "Il la prend"}]},
        "L12": {"title": "Plus Haut", "artist": "Claude Francois", "yt": "0wGvGVJPj-c", "level": "A1+",
            "vocab": ["plus", "haut", "toujours"],
            "fill": [{"line": "Plus ___", "ans": "haut"}, {"line": "Toujours plus ___", "ans": "haut"}],
            "quiz": [{"q": "Ou veut-il aller?", "a": "Plus haut"}, {"q": "Que veut-il toujours?", "a": "Plus haut"}]},
        "L13": {"title": "Que Je T'aime", "artist": "Johnny Hallyday", "yt": "M4CJvHjVbqM", "level": "A1+",
            "vocab": ["que je t'aime", "amour", "toujours"],
            "fill": [{"line": "Que je t'___", "ans": "aime"}, {"line": "Que je t'aime, que je t'aime", "ans": "aime"}],
            "quiz": [{"q": "Qu'est-ce qu'il dit?", "a": "Que je t'aime"}, {"q": "Combien de fois?", "a": "Repete plusieurs fois"}]},
        "L14": {"title": "Mistral Gagnant", "artist": "Renaud", "yt": "QnvG2A8c1Z8", "level": "A1+",
            "vocab": ["mistral", "gagnant", "temps"],
            "fill": [{"line": "Le mistral ___", "ans": "gagnant"}, {"line": "Le temps d'un ___", "ans": "sourire"}],
            "quiz": [{"q": "Quel est le nom?", "a": "Mistral gagnant"}, {"q": "Combien de temps?", "a": "Le temps d'un sourire"}]},
        "L15": {"title": "Comme d'Habitude", "artist": "Claude Francois", "yt": "NqeOwLErL3U", "level": "A1+",
            "vocab": ["comme", "habitude", "matin"],
            "fill": [{"line": "Comme d'___", "ans": "habitude"}, {"line": "Je me leve et je te ___", "ans": "bouscule"}],
            "quiz": [{"q": "Comment est la routine?", "a": "Comme d'habitude"}, {"q": "Que fait-il au matin?", "a": "Il se leve"}]},
        "L16": {"title": "Je Te Promets", "artist": "Johnny Hallyday", "yt": "8vY1lnCp0a4", "level": "A1+",
            "vocab": ["je te promets", "avenir", "toujours"],
            "fill": [{"line": "Je te ___", "ans": "promets"}, {"line": "Pour ___", "ans": "toujours"}],
            "quiz": [{"q": "Que fait le chanteur?", "a": "Il promet"}, {"q": "Pour combien de temps?", "a": "Pour toujours"}]},
        "L17": {"title": "Je Voudrais", "artist": "Traditionnel", "yt": "9bZkp7q19f0", "level": "A1+",
            "vocab": ["je voudrais", "aimer", "s'il vous plait"],
            "fill": [{"line": "Je ___ un cafe", "ans": "voudrais"}, {"line": "S'il vous ___", "ans": "plait"}],
            "quiz": [{"q": "Que veut-il?", "a": "Un cafe"}, {"q": "Comment demande-t-il?", "a": "S'il vous plait"}]},
        "L18": {"title": "Le Chanteur", "artist": "Daniel Balavoine", "yt": "JvGdZk3Y4bQ", "level": "A1+",
            "vocab": ["le chanteur", "qui", "monde"],
            "fill": [{"line": "Le ___ qui chante", "ans": "chanteur"}, {"line": "Pour tout le ___", "ans": "monde"}],
            "quiz": [{"q": "Qui est le sujet?", "a": "Le chanteur"}, {"q": "Pour qui chante-t-il?", "a": "Pour tout le monde"}]},
        "L19": {"title": "On Ecrit Sur Les Murs", "artist": "Kids United", "yt": "R1JBQqLMVAM", "level": "A1+",
            "vocab": ["on ecrit", "murs", "espoir"],
            "fill": [{"line": "On ecrit sur les ___", "ans": "murs"}, {"line": "Le nom de ceux qu'on ___", "ans": "aime"}],
            "quiz": [{"q": "Ou ecrit-on?", "a": "Sur les murs"}, {"q": "Quoi?", "a": "Le nom de ceux qu'on aime"}]}
    }
}